#!/bin/bash
# open-fuse-iso (CLI terminal only)
# mount image file in new folder, unmount if mounted already
# requires fuseiso
# original credits for open-iso.sh script go to johnraff on crunchbang.org
# open-fuse-iso is GPL2
shopt -s nocasematch
[[ -f $1 ]] && [[ $1 =~ \.(iso|bin|mdf|img|nrg)$ ]] || { echo "Mount/Unmount $1 is not a supported file type"; exit 1 ;}
shopt -u nocasematch
foldername=${1}.mount
if grep "^fuseiso[[:space:]]$(readlink -f $foldername)" /etc/mtab >/dev/null
then
fusermount -u "$foldername" || { echo "Mount/Unmount failed to unmount $1"; exit 1;}
echo "Mount/Unmount $1 has been unmounted"
else
[[ -d $foldername ]] && [[ $( ls -A $foldername ) ]] && { echo "Mount/Unmount $foldername is not empty" ; exit 1 ;}
fuseiso -p "$1" "$foldername" || { echo "Mount/Unmount failed to mount $1"; exit 1;}
echo "Mount/Unmount $1 has been mounted on $foldername"
fi
exit
